<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Outputs" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-07-15">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="Momentary_on" Comment="Tastend Softkey 5000 auf Q1" x="-266.6666666666667" y="-933.3333333333334">
			<SubAppInterfaceList>
				<SubAppEventInputs>
					<SubAppEvent Name="INIT" Type="Event" Comment="">
					</SubAppEvent>
				</SubAppEventInputs>
			</SubAppInterfaceList>
			<SubAppNetwork>
				<FB Name="SoftKey_5000" Type="IX" Comment="" x="353.33333333333337" y="320.0">
					<Parameter Name="QI" Value="TRUE"/>
				</FB>
				<FB Name="DigitalOutput_Q1" Type="QX" Comment="" x="2780.0" y="320.0">
					<Parameter Name="QI" Value="TRUE"/>
				</FB>
				<SubApp Name="GreenWhiteBackground1" Type="GreenWhiteBackground1" Comment="" x="2780.0" y="1306.6666666666667">
					<Parameter Name="u16ObjId" Value="SoftKey_5000"/>
				</SubApp>
				<EventConnections>
					<Connection Source="SoftKey_5000.IND" Destination="DigitalOutput_Q1.REQ" Comment="" dx1="440.0"/>
					<Connection Source="INIT" Destination="SoftKey_5000.INIT" Comment="" dx1="200.0">
						<Attribute Name="Visible" Type="STRING" Value="false"/>
					</Connection>
					<Connection Source="INIT" Destination="GreenWhiteBackground1.INIT" Comment="" dx1="1366.6666666666667">
						<Attribute Name="Visible" Type="STRING" Value="false"/>
					</Connection>
					<Connection Source="SoftKey_5000.IND" Destination="GreenWhiteBackground1.REQ" Comment="" dx1="413.33333333333337"/>
					<Connection Source="SoftKey_5000.INITO" Destination="DigitalOutput_Q1.INIT" Comment=""/>
				</EventConnections>
				<DataConnections>
					<Connection Source="SoftKey_5000.IN" Destination="DigitalOutput_Q1.OUT" Comment="" dx1="80.0"/>
					<Connection Source="SoftKey_5000.IN" Destination="GreenWhiteBackground1.DI1" Comment="" dx1="80.0"/>
				</DataConnections>
			</SubAppNetwork>
			<Attribute Name="Unfolded" Type="STRING" Value="true"/>
			<Attribute Name="width" Type="LREAL" Value="4806.666666666667"/>
			<Attribute Name="height" Type="LREAL" Value="2806.666666666667"/>
		</SubApp>
		<SubApp Name="Toggle_on" Comment="T-Flip-Flop Softkey 5001 auf Q2" x="-266.6666666666667" y="2000.0">
			<SubAppInterfaceList>
				<SubAppEventInputs>
					<SubAppEvent Name="INIT" Type="Event" Comment="">
					</SubAppEvent>
				</SubAppEventInputs>
			</SubAppInterfaceList>
			<SubAppNetwork>
				<FB Name="SoftKey_5001" Type="IX" Comment="" x="353.33333333333337" y="320.0">
					<Parameter Name="QI" Value="TRUE"/>
				</FB>
				<FB Name="DigitalOutput_Q2" Type="QX" Comment="" x="5420.0" y="320.0">
					<Parameter Name="QI" Value="TRUE"/>
				</FB>
				<SubApp Name="GreenWhiteBackground1" Type="GreenWhiteBackground1" Comment="" x="5553.333333333334" y="1386.6666666666667">
					<Parameter Name="u16ObjId" Value="SoftKey_5001"/>
				</SubApp>
				<FB Name="E_SWITCH" Type="E_SWITCH" Comment="" x="2353.3333333333335" y="586.6666666666667">
				</FB>
				<FB Name="E_T_FF" Type="E_T_FF" Comment="" x="4220.0" y="586.6666666666667">
				</FB>
				<EventConnections>
					<Connection Source="INIT" Destination="SoftKey_5001.INIT" Comment="" dx1="200.0">
						<Attribute Name="Visible" Type="STRING" Value="false"/>
					</Connection>
					<Connection Source="INIT" Destination="GreenWhiteBackground1.INIT" Comment="" dx1="1366.6666666666667">
						<Attribute Name="Visible" Type="STRING" Value="false"/>
					</Connection>
					<Connection Source="SoftKey_5001.IND" Destination="E_SWITCH.EI" Comment="" dx1="653.3333333333334"/>
					<Connection Source="E_SWITCH.EO1" Destination="E_T_FF.CLK" Comment="" dx1="580.0"/>
					<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q2.REQ" Comment="" dx1="353.33333333333337"/>
					<Connection Source="SoftKey_5001.INITO" Destination="DigitalOutput_Q2.INIT" Comment=""/>
					<Connection Source="E_T_FF.EO" Destination="GreenWhiteBackground1.REQ" Comment="" dx1="366.6666666666667"/>
				</EventConnections>
				<DataConnections>
					<Connection Source="SoftKey_5001.IN" Destination="E_SWITCH.G" Comment="" dx1="653.3333333333334"/>
					<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q2.OUT" Comment="" dx1="353.33333333333337"/>
					<Connection Source="E_T_FF.Q" Destination="GreenWhiteBackground1.DI1" Comment="" dx1="186.66666666666669"/>
				</DataConnections>
			</SubAppNetwork>
			<Attribute Name="Unfolded" Type="STRING" Value="true"/>
			<Attribute Name="width" Type="LREAL" Value="8140.0"/>
			<Attribute Name="height" Type="LREAL" Value="2806.666666666667"/>
		</SubApp>
		<SubApp Name="RS_FF" Comment="T-Flip-Flop Softkey 5002/3 auf Q3" x="-266.6666666666667" y="4933.333333333334">
			<SubAppInterfaceList>
				<SubAppEventInputs>
					<SubAppEvent Name="INIT" Type="Event" Comment="">
					</SubAppEvent>
				</SubAppEventInputs>
			</SubAppInterfaceList>
			<SubAppNetwork>
				<FB Name="SoftKey_5002" Type="IX" Comment="" x="353.33333333333337" y="320.0">
					<Parameter Name="QI" Value="TRUE"/>
				</FB>
				<FB Name="DigitalOutput_Q3" Type="QX" Comment="" x="5553.333333333334" y="320.0">
					<Parameter Name="QI" Value="TRUE"/>
				</FB>
				<SubApp Name="GreenWhiteBackground1" Type="GreenWhiteBackground1" Comment="" x="5553.333333333334" y="1653.3333333333335">
					<Parameter Name="u16ObjId" Value="SoftKey_5002"/>
				</SubApp>
				<FB Name="E_SWITCH_02" Type="E_SWITCH" Comment="" x="1686.6666666666667" y="586.6666666666667">
				</FB>
				<FB Name="SoftKey_5003" Type="IX" Comment="" x="353.33333333333337" y="1653.3333333333335">
					<Parameter Name="QI" Value="TRUE"/>
				</FB>
				<FB Name="E_SWITCH_03" Type="E_SWITCH" Comment="" x="1686.6666666666667" y="1920.0">
				</FB>
				<FB Name="E_SR" Type="E_SR" Comment="" x="3686.666666666667" y="1253.3333333333335">
				</FB>
				<EventConnections>
					<Connection Source="INIT" Destination="SoftKey_5002.INIT" Comment="" dx1="200.0">
						<Attribute Name="Visible" Type="STRING" Value="false"/>
					</Connection>
					<Connection Source="INIT" Destination="GreenWhiteBackground1.INIT" Comment="" dx1="1366.6666666666667">
						<Attribute Name="Visible" Type="STRING" Value="false"/>
					</Connection>
					<Connection Source="SoftKey_5002.IND" Destination="E_SWITCH_02.EI" Comment="" dx1="566.6666666666667"/>
					<Connection Source="SoftKey_5002.INITO" Destination="DigitalOutput_Q3.INIT" Comment=""/>
					<Connection Source="SoftKey_5003.IND" Destination="E_SWITCH_03.EI" Comment="" dx1="566.6666666666667" dx2="566.6666666666667" dy="0.0"/>
					<Connection Source="E_SWITCH_02.EO1" Destination="E_SR.S" Comment="" dx1="693.3333333333334"/>
					<Connection Source="E_SWITCH_03.EO1" Destination="E_SR.R" Comment="" dx1="693.3333333333334"/>
					<Connection Source="E_SR.EO" Destination="DigitalOutput_Q3.REQ" Comment="" dx1="620.0"/>
					<Connection Source="E_SR.EO" Destination="GreenWhiteBackground1.REQ" Comment="" dx1="673.3333333333334"/>
					<Connection Source="INIT" Destination="SoftKey_5003.INIT" Comment="" dx1="200.0">
						<Attribute Name="Visible" Type="STRING" Value="false"/>
					</Connection>
				</EventConnections>
				<DataConnections>
					<Connection Source="SoftKey_5002.IN" Destination="E_SWITCH_02.G" Comment="" dx1="566.6666666666667"/>
					<Connection Source="SoftKey_5003.IN" Destination="E_SWITCH_03.G" Comment="" dx1="566.6666666666667" dx2="566.6666666666667" dy="0.0"/>
					<Connection Source="E_SR.Q" Destination="DigitalOutput_Q3.OUT" Comment="" dx1="880.0"/>
					<Connection Source="E_SR.Q" Destination="GreenWhiteBackground1.DI1" Comment="" dx1="880.0"/>
				</DataConnections>
			</SubAppNetwork>
			<Attribute Name="Unfolded" Type="STRING" Value="true"/>
			<Attribute Name="width" Type="LREAL" Value="8273.333333333334"/>
			<Attribute Name="height" Type="LREAL" Value="3473.3333333333335"/>
		</SubApp>
		<SubApp Name="Momentary_on_1" Comment="Tastend Softkey 5004 und I1 auf Q1 (OR Verknüpfung)" x="4800.0" y="-933.3333333333334">
			<SubAppInterfaceList>
				<SubAppEventInputs>
					<SubAppEvent Name="INIT" Type="Event" Comment="">
					</SubAppEvent>
				</SubAppEventInputs>
			</SubAppInterfaceList>
			<SubAppNetwork>
				<FB Name="SoftKey_5004" Type="IX" Comment="" x="400.0" y="320.0">
					<Parameter Name="QI" Value="TRUE"/>
				</FB>
				<FB Name="DigitalOutput_Q4" Type="QX" Comment="" x="4400.0" y="320.0">
					<Parameter Name="QI" Value="TRUE"/>
				</FB>
				<SubApp Name="GreenWhiteBackground1" Type="GreenWhiteBackground1" Comment="" x="4400.0" y="1306.6666666666667">
					<Parameter Name="u16ObjId" Value="SoftKey_5004"/>
				</SubApp>
				<FB Name="DigitalInput_I1" Type="IX" Comment="" x="400.0" y="1386.6666666666667">
					<Parameter Name="QI" Value="TRUE"/>
				</FB>
				<FB Name="OR_2" Type="OR_2" Comment="" x="2133.3333333333335" y="853.3333333333334">
				</FB>
				<EventConnections>
					<Connection Source="INIT" Destination="SoftKey_5004.INIT" Comment="" dx1="200.0">
						<Attribute Name="Visible" Type="STRING" Value="false"/>
					</Connection>
					<Connection Source="INIT" Destination="GreenWhiteBackground1.INIT" Comment="" dx1="1366.6666666666667">
						<Attribute Name="Visible" Type="STRING" Value="false"/>
					</Connection>
					<Connection Source="SoftKey_5004.INITO" Destination="DigitalOutput_Q4.INIT" Comment=""/>
					<Connection Source="INIT" Destination="DigitalInput_I1.INIT" Comment="" dx1="226.66666666666669">
						<Attribute Name="Visible" Type="STRING" Value="false"/>
					</Connection>
					<Connection Source="SoftKey_5004.IND" Destination="OR_2.REQ" Comment="" dx1="320.0"/>
					<Connection Source="DigitalInput_I1.IND" Destination="OR_2.REQ" Comment="" dx1="286.6666666666667"/>
					<Connection Source="OR_2.CNF" Destination="DigitalOutput_Q4.REQ" Comment="" dx1="466.6666666666667"/>
					<Connection Source="OR_2.CNF" Destination="GreenWhiteBackground1.REQ" Comment="" dx1="473.33333333333337"/>
				</EventConnections>
				<DataConnections>
					<Connection Source="SoftKey_5004.IN" Destination="OR_2.IN1" Comment="" dx1="520.0"/>
					<Connection Source="DigitalInput_I1.IN" Destination="OR_2.IN2" Comment="" dx1="520.0"/>
					<Connection Source="OR_2.OUT" Destination="DigitalOutput_Q4.OUT" Comment="" dx1="913.3333333333334"/>
					<Connection Source="OR_2.OUT" Destination="GreenWhiteBackground1.DI1" Comment="" dx1="900.0"/>
				</DataConnections>
			</SubAppNetwork>
			<Attribute Name="Unfolded" Type="STRING" Value="true"/>
			<Attribute Name="width" Type="LREAL" Value="6986.666666666667"/>
			<Attribute Name="height" Type="LREAL" Value="2806.666666666667"/>
		</SubApp>
		<EventConnections>
			<Connection Source="INIT" Destination="Momentary_on.INIT" Comment="" dx1="766.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Toggle_on.INIT" Comment="" dx1="533.3333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="RS_FF.INIT" Comment="" dx1="933.3333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Momentary_on_1.INIT" Comment="" dx1="3066.666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
